# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: exercise


on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-18.04 # runs a test on Ubuntu, Windows and macOS

    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
            for file in `ls $1`
            do
              if [ -d $1"/"$file ]
              then
                ergodic $1"/"$file
              else
                local path=$1"/"$file 
                local name=$file      
                local size=`du --max-depth=1 $path|awk '{print $1}'` 
                echo $name  $size $path 
              fi
            done
          done