# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: exercise


on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-18.04 # runs a test on Ubuntu, Windows and macOS

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: ngiq-component
      - name: Setup Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          cd ../excerseDemo
          echo "=====================";
          echo "["`date +%Y-%m-%d--%H:%M:%S`"]获取当前目录的所有文件及文件夹名字脚本 author 小白杨" ;
          echo "["`date +%Y-%m-%d--%H:%M:%S`"]开始执行";
          ##获取自身的名称
              selfname=`basename $0`
              echo $selfname;
              x=0;
              cd ..;
            for filename in *;
              do         #循环当前目录下的文件
                array[$x]=$filename   #文件名给数组索引为x的元素
                let "x+=1"      #改变索引指针，步长1
                echo $filename;
          done
          echo ${array[@]};
          echo "["`date +%Y-%m-%d--%H:%M:%S`"]执行结束";
          echo "=============================================";